# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [2]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo: 
arr_0_to_9 = np.arange(10)
print(arr_0_to_9)

[0 1 2 3 4 5 6 7 8 9]


Tuve que buscar en internet una forma en la que numpy haga eso por si acaso y si la tenía. Simplemente tengo que indicarle el numero entero de tope.

**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [6]:
#todo:
arr_5_zeros = np.zeros(5)
print(arr_5_zeros)

arr_5_zeros[2] = 5
print(arr_5_zeros)


[0. 0. 0. 0. 0.]
[0. 0. 5. 0. 0.]


El metodo estaba en el documento que nos proporcionó el profe agustín. Indiqué el indice "2" porque coloquialmente  es el tercer elemento.

**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [ ]:
#todo: 
rand_np_matrix = np.random.rand(3,3)
print(rand_np_matrix)

array([[0.42371899, 0.09133755, 0.43809761],
       [0.52976121, 0.2323543 , 0.08388166],
       [0.73258459, 0.4729488 , 0.13406204]])

Tambien ya estaba este mismo ejemplo en el documento del profe agustín, fue tan simple como indicar las dimensiones de la matriz. 

**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [23]:
#todo:
arr = np.array([10, 20, 30, 40, 50])
print(arr)
plus_5 = arr + 5
print(plus_5)
random_number = np.random.randint(0, 10)
print(random_number)
then_mult_rand = plus_5 * random_number
print(then_mult_rand)

[10 20 30 40 50]
[15 25 35 45 55]
1
[15 25 35 45 55]


Fui mostrando paso a paso el proceso del array y el resultado de las opeciones que se le hace a cada elemento del mismo.

**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:
matrix_identity = np.eye(4)
print(matrix_identity)

matrix_identity_2 = np.zeros((4,4), dtype=int)
for i in range(4):
    matrix_identity_2[i][i] = 1
print(matrix_identity_2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


He visto que existe el metodo de np que te hace ya la matriz identidad pero también quise hacerlo de forma manual ya que es tan simple. Cada ciclo ya que los valores de las dimensiones de cada elemento de la diagonal son iguales sólo hay que hacer un "for i" e ir cambiando los ceros por uno. 

**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [31]:
#todo: 
even_n_arr = np.arange(0, 20, 2)

print(even_n_arr)
addition = even_n_arr + random_number
print(addition)
subtraction = even_n_arr - random_number
print(subtraction)
multiplication = even_n_arr * random_number
print(multiplication)
division = even_n_arr / random_number
print(division)

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[-1  1  3  5  7  9 11 13 15 17]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


Pude hacer la matriz vector simplemente agregando "paso 2" y sumando cada elemento de la matrix original por un numero aleatorio previamente definido.